[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/v1/webhook/github"
  to = "/.netlify/functions/github-webhook"
  status = 200
  force = true